### ISSUE TITLE
the question of the lincRNA loci about the paper "The Long Intergenic Noncoding RNA (LincRNA) Landscape of the Soybean Genome" ?

### ISSUE THREAD

**Issue by Liyi56** [agolicz/lncRNAs-Plots#1]
Excuse me, I am a rookie in lincRNA analyzing. I am very sorry that contact with you by this way! 
when I see your paper (The Long Intergenic Noncoding RNA (LincRNA) Landscape of the Soybean Genome),     I got some enlighten and had many question at the same time. I hope someone can help me!
    about the point "If the putative lncRNAgene did not overlap any coding loci, it was considered a lincRNA gene.",  the question is the the mRNA and new possiable lincRNA transripts annotation of stringtie_merged_gtf  have so many unindentified strand(p.s + - .  there are 3 type about the direction ), in another word, how can I judge whether the coding loci overlap with lincRNA loci, if they haven't the same direction(p.s + - .  I think"+","-"  represents two different directions relative to the transcription direction,and the"." is means that it can't judge it )
   I hope you can read this message !!!!  very very thanks to you!!

**Comment by agolicz** [comment]
Hi,
No problem at all. There are different types of lncRNAs (1) lncRNAs which
overlap coding genes, it can be on the same or opposite strand (2) lincRNAs
(long intergenic lncRNAs) which do not overlap protein coding genes
regardless of strand - the coordinates of coding genes and lincRNAs never
overlap. Because we had no strand information we limited the analysis to
lincRNAs. That way you can ensure that none of the coordinates overlap
regardless of  strand, so the direction of transcription does not matter.
Hope that helps,
Agnieszka

**Comment by Liyi56** [comment]
I got it! it's so nice of you!!
